### ISSUE TITLE
Setting Mock Locations  Error: Not found; no service started.

### ISSUE THREAD

**Issue by yaoliangcui** [appium/io.appium.settings#109]
Phone：HUAWEI Y9 Prime 2019
STK-LX3
EMUI=10.0.0
Android=10

Setting Mock Locations
>adb shell am startservice --user 0 -n io.appium.settings/.LocationService --es longitude -87.12733 --es latitude 15.13697

>Starting service: Intent { cmp=io.appium.settings/.LocationService (has extras) }
>Error: Not found; no service started.

![WX20230421-170017@2x](https://user-images.githubusercontent.com/38241880/233593945-a017b235-44b2-414b-87de-69a380354ab6.png)

**Comment by yaoliangcui** [comment]
![image](https://user-images.githubusercontent.com/38241880/233624106-4d1de57d-909f-4cfe-8485-d5d1d673b3f7.png)

When I try to remove this section, then run "adb shell am stopservice io.appium.settings/.LocationService" and try again to modify the location "adb shell am start-foreground-service --user 0 -n io.appium.settings/.LocationService --es longitude 135.5138155 --es latitude 34.7072415", the prompt is passed; The modification is successfully located.

**Comment by KazuCocoa** [comment]
Was io.appium.settings running when the device got `Error: Not found; no service started.` error?
I wondered if the settings app was not started as a foreground service. (so, the device's notification did not have io.appium.settings app's foreground service notification)

**Comment by KazuCocoa** [comment]
Please try out uia2 driver 2.40.1.
