### ISSUE TITLE
.LocationService throwing Error: Not found; no service started.

### ISSUE THREAD

**Issue by jccdg1995** [appium/io.appium.settings#122]
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: Error executing adbExec. Original error: 'Command '/Users/jerome/Library/Android/sdk/platform-tools/adb -P 5037 -s 26184d7b27057ece shell am start-foreground-service -e longitude 103.8448 -e latitude 1.3709 -e altitude 0 io.appium.settings/.LocationService' exited with code 255'; Command output: Error: Not found; no service started.

This error has been consistently occurring. Device has no issues since it worked before upgrading to JDK 17 + Appium 2.1.3

**Comment by KazuCocoa** [comment]
Please try out uia2 driver `2.40.1`. It looks like the settings app was not running as a foreground service. The latest one fixed a foreground service detection, so a new session request would launch the settings app properly
