### ISSUE TITLE
Unable to read Unicode IME on Android devices

### ISSUE THREAD

**Issue by kuangyi126** [appium/io.appium.settings#202]
testing environment: 
appium v1.22
Appium settings v3.4.0 (other versions also have the same issue)

After installing AppiumSettings, when loading the system's available keyboards on Android devices, Unicode IME may not be able to read them
Reason: 
Unable to retrieve the specified Subtype in Unicode IME, resulting in the following exception
11-28 12:15:18.562 E/AndroidRuntime(24398): java.lang.RuntimeException: Unable to start service  com.android.settings.smartsettings.UpdateService@b813510   with Intent { cmp=com.android.settings/.smartsettings.UpdateService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.inputmethod.InputMethodSubtype.hashCode()' on a null object reference

Countermeasure: 
If it is not possible to directly modify the Android device code, set the SubType property in Unicode IME and modify it as follows 
app/src/main/res/xml/method.xml (in subtype)

```
<?xml version="1.0" encoding="utf-8"?>
<input-method xmlns: android=" http://schemas.android.com/apk/res/android " >
<subtype
android:label="@string/subtype_label_qwerty"
android:imeSubtypeLocale="en_US"
android:imeSubtypeMode="keyboard"
android:imeSubtypeExtraValue="KeyboardLayoutSet=qwerty"  />
<subtype
android:label="@string/subtype_label_numeric"
android:imeSubtypeLocale="und_001"
android:imeSubtypeMode="keyboard"
android:imeSubtypeExtraValue="KeyboardLayoutSet=numeric" />
</input-method>
```

Questions:
1. Is this a bug in the appiumsettings program
2. Can we modify according to the above measures? Will it affect other functions
3. Regarding the above issues, what are the corresponding methods for appiumsettings to avoid NullPointer Exception on the application side

**Comment by KazuCocoa** [comment]
Please use the latest appium, uia2 driver and settings etc first. The reported Appium 1.22 is outdated. Then, please attach logs.

**Comment by kuangyi126** [comment]
@KazuCocoa  Thank you for your reply
From the phenomenon of the problem, it seems that it is not directly related to the appium version, but rather caused by the use of Unicode IME in io.appium.settings during automated testing
1. On Android devices, the latest io. appium. settings (v5.12.19) and appium uiautomator2 server (v7.1.9) were installed, but manual testing still encountered the aforementioned issues
2. After uninstalling io. appium. settings (v5.12.19), the issue has been resolved
3. After modifying io.appium.settings according to the above measures, reinstall and solve the problem
![image](https://github.com/user-attachments/assets/98899cae-7577-4d0d-a048-c1d0b1d16202)


logcat
`--------- beginning of crash
01-03 17:37:51.798 E/AndroidRuntime(31328): FATAL EXCEPTION: main
01-03 17:37:51.798 E/AndroidRuntime(31328): Process: com.android.settings, PID: 31328
01-03 17:37:51.798 E/AndroidRuntime(31328): java.lang.RuntimeException: Unable to start service com.android.settings.smartsettings.UpdateService@3a5cc27 with Intent { cmp=com.android.settings/.smartsettings.UpdateService (has extras) }: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.inputmethod.InputMethodSubtype.hashCode()' on a null object reference
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4118)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.app.ActivityThread.access$1800(ActivityThread.java:219)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1895)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.os.Looper.loop(Looper.java:214)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.app.ActivityThread.main(ActivityThread.java:7369)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at java.lang.reflect.Method.invoke(Native Method)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
01-03 17:37:51.798 E/AndroidRuntime(31328): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.inputmethod.InputMethodSubtype.hashCode()' on a null object reference
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.settings.smartsettings.items.DefaultIME.getCurrentSubTypeHashCode(DefaultIME.java:175)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.settings.smartsettings.items.DefaultIME.createValueMap(DefaultIME.java:165)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.settings.smartsettings.items.DefaultIME.intentGet(DefaultIME.java:93)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.settings.smartsettings.UpdateService.intentGetReq(UpdateService.java:96)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at com.android.settings.smartsettings.UpdateService.onStartCommand(UpdateService.java:49)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4100)
01-03 17:37:51.798 E/AndroidRuntime(31328): 	... 8 more
01-03 17:37:51.804 I/Process (31328): Sending signal. PID: 31328 SIG: 9
`
