### ISSUE TITLE
Cannot get version 2.14.0 apk

### ISSUE THREAD

**Issue by nunessf** [appium/io.appium.settings#39]
Hi,

Your latest release (v2.14.0) source code zip doesn't contain the folder "apks".
How can I download this version apk?

Thank you

**Comment by imurchie** [comment]
They are in the npm package (https://www.npmjs.com/package/io.appium.settings). You can download the tarball using `npm pack io.appium.settings`, or else just `npm install io.appium.settings` and then look in `node_modules/io.appium.settings`.

Alternatively, you can build them from source by cloning the package and running `npm install`..
