### ISSUE TITLE
Enable/Disable Data Network doesn't work on Android 5.0+

### ISSUE THREAD

**Issue by chenhengjie123** [appium/io.appium.settings#5]
For now this app use hidden API `setMobileDataEnabled` of `ConnectivityManager` on Android 2.3+. However, this hidden API is removed on Android 5.0+, so it doesn't work.

I also found [an issue on stackoverflow](http://stackoverflow.com/questions/29340150/android-l-5-x-turn-on-off-mobile-data-programmatically) that discuss this:

> In Android L 5.xx the hidden API setMobileDataEnabled method is
> removed and it can no longer be used. You can verify this in android
> lolipop source code under
> /frameworks/base/core/java/android/net/ConnectivityManager.java.
> 
> If you still insist to perform it, you can use code snippet answered
> by Kushal but getDataEnabled is a system api, which normal user
> applications cant access. There is also one more system api available
> setDataEnabled under TelephonyManager.
> (/frameworks/base/telephony/java/android/telephony/TelephonyManager.java)

Also a possible solution here: http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later

For now this setting application cannot enable/disable data network, so I suggest adding description of this issue in document [network_connection](https://github.com/appium/appium/blob/master/docs/en/writing-running-appium/network_connection.md) first.

**Comment by scottdixon** [comment]
Related: https://github.com/appium/appium-android-driver/issues/98

**Comment by mykola-mokhnach** [comment]
Should be fixed by https://github.com/appium/io.appium.settings/pull/7. Please try it and see if it works for you. Data connection handling has been implemented exactly the way it is described by http://stackoverflow.com/questions/26539445/the-setmobiledataenabled-method-is-no-longer-callable-as-of-android-l-and-later, which means it won't work on non-rooted devices running Lollipop+ anyway.
