### ISSUE TITLE
How to ensure latest appium settings app(which is 4.0.0 now) is installed when initialize driver

### ISSUE THREAD

**Issue by sincethenn** [appium/io.appium.settings#78]
I use latest Appium desktop and latest Appium-Python-Client
But after initializing driver, 3.4.0 version of io.appium.settings app is installed rather than latest 4.0.0

**Comment by sincethenn** [comment]
I know how to get current version. But I wanna know whether exist io.appium.settings apk version configuration item in Appium(eg. in desired capability)

or if I want to use latest version of io.appium.settings apk, I must clone this repo and build an apk.
And every time after I init driver webdriver.Remote("http://localhost:4723/wd/hub", desired_caps), need manual check version matched and then install?

**Comment by KazuCocoa** [comment]
it depends on the package version of uia2/espresso driver. Each package has proper settings app version as their dependencies, so basically they handle it.

If you'd like to install an arbitrary version, you need to manage the settings apk by yourself. Then, `appium:skipDeviceInitialization` allows you to skip the preparation steps by Appium.
