### ISSUE TITLE
Add latests build to release page

### ISSUE THREAD

**Issue by fleytman** [appium/io.appium.settings#79]
Pls add latests build to [release](https://github.com/appium/io.appium.settings/releases) page

**Comment by fleytman** [comment]
My build https://github.com/fleytman/io.appium.settings/releases/tag/v4.0.0

**Comment by KazuCocoa** [comment]
Thank you.
Semantic release task will create it: https://github.com/appium/io.appium.settings/releases

**Comment by fleytman** [comment]
I not see apk file in Assets
<details><summary>Screenshot</summary><img width="697" alt="Screenshot 2022-03-16 at 23 04 08" src="https://user-images.githubusercontent.com/1923645/158680641-b7884ba6-24db-4515-bab2-5a5692f68b04.png"></details>

**Comment by KazuCocoa** [comment]
ah, I see. Thought just a release page.
this module expects to get via npm for now as Appium.
let me label as help wanted. 
Probably https://github.com/appium/io.appium.settings/blob/master/.github/workflows/publish.js.yml need some update.

**Comment by fleytman** [comment]
I saw that an apk was added for the old version. 
<details><summary>screenshot</summary><img width="646" alt="Screenshot 2022-03-16 at 23 15 28" src="https://user-images.githubusercontent.com/1923645/158682665-792449fe-6f4a-429a-9934-9ebef518757e.png"></details>

Thought I'd just hand-edit the release and put the current build in.
If I have time, I can look into how to do this automatically from CI.

**Comment by fleytman** [comment]
@KazuCocoa Can you try modify .releaserc?
Doc here https://github.com/semantic-release/github

**Comment by KazuCocoa** [comment]
yes, i found the assets in https://github.com/semantic-release/semantic-release/blob/master/docs/usage/plugins.md#plugin-options-configuration . I saw git's one.
