### ISSUE TITLE
Not work switch locale from readme

### ISSUE THREAD

**Issue by fleytman** [appium/io.appium.settings#80]
> Set particular locale:
> 
> $ adb shell am broadcast -a io.appium.settings.locale --es lang ja --es country JP
> $ adb shell getprop persist.sys.locale # ja-JP
> $ adb shell am broadcast -a io.appium.settings.locale --es lang zh --es country CN --es script Hans
> $ adb shell getprop persist.sys.locale # zh-Hans-CN for API level 21+

My test
```
➜  ~ adb shell am broadcast -a io.appium.settings.locale --es lang ru --es country RU
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 (has extras) }
Broadcast completed: result=0
➜  ~ adb shell getprop persist.sys.locale
en-US
```

But appium use
```
➜  ~ adb shell am broadcast -a io.appium.settings.locale -n io.appium.settings/.receivers.LocaleSettingReceiver --es lang ru --es country RU
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 cmp=io.appium.settings/.receivers.LocaleSettingReceiver (has extras) }
Broadcast completed: result=0
```
And it work
```
➜  ~ adb shell getprop persist.sys.locale
ru-RU
```

Pls fix readme

**Comment by KazuCocoa** [comment]
the package name is not necessary. Maybe the settings app did not run at your first time:

```
% adb shell am broadcast -a io.appium.settings.locale --es lang ru --es country RU
Broadcasting: Intent { act=io.appium.settings.locale flg=0x400000 (has extras) }
Broadcast completed: result=0
kazuaki@kazus-MB-pro tmp % adb shell getprop persist.sys.locale
ru-RU
```

**Comment by KazuCocoa** [comment]
I see, thank you.
I recently tested some real devices in a couple of os versions, so it might depend on devices.
README also can address it as well.
