### ISSUE TITLE
Can io.appium.settings set locale of any installed app?

### ISSUE THREAD

**Issue by LeeBinder** [appium/io.appium.settings#86]
Hello Appium team. Reading the documentation I am unsure if the appium settings app can be used to set the language of an installed app. If it can: lets say the app's identifier is `some.app`, how would the command look like?

**Comment by KazuCocoa** [comment]
this sets system locale/language, not only an app

**Comment by LeeBinder** [comment]
oh sorry, I was positive I had replied to you before right when you commented, very strange. Anyway, thanks for answering my question.
